[package]
name = "namada_vp_env"
description = "Namada validity predicate execution environment"
resolver = "2"
authors.workspace = true
edition.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
namada_core.workspace = true
namada_gas.workspace = true
namada_events.workspace = true
namada_storage.workspace = true
namada_tx.workspace = true

derivative.workspace = true
masp_primitives.workspace = true
smooth-operator.workspace = true
