# Token accounts with their validity predicates

[token.NAM]
denom = 6

[token.NAM.masp_params]
max_reward_rate = "0.01"
kd_gain_nom = "0.25"
kp_gain_nom = "0.25"
locked_amount_target = 10000

[token.BTC]
denom = 8

[token.BTC.masp_params]
max_reward_rate = "0.01"
kd_gain_nom = "0.25"
kp_gain_nom = "0.25"
locked_amount_target = 10000

[token.ETH]
denom = 18

[token.ETH.masp_params]
max_reward_rate = "0.01"
kd_gain_nom = "0.25"
kp_gain_nom = "0.25"
locked_amount_target = 10000

[token.DOT]
denom = 10

[token.DOT.masp_params]
max_reward_rate = "0.01"
kd_gain_nom = "0.25"
kp_gain_nom = "0.25"
locked_amount_target = 10000

[token.Schnitzel]
denom = 6

[token.Schnitzel.masp_params]
max_reward_rate = "0.01"
kd_gain_nom = "0.25"
kp_gain_nom = "0.25"
locked_amount_target = 10000

[token.Apfel]
denom = 6

[token.Apfel.masp_params]
max_reward_rate = "0.01"
kd_gain_nom = "0.25"
kp_gain_nom = "0.25"
locked_amount_target = 10000

[token.Kartoffel]
denom = 6

[token.Kartoffel.masp_params]
max_reward_rate = "0.01"
kd_gain_nom = "0.25"
kp_gain_nom = "0.25"
locked_amount_target = 10000
