[package]
name = "namada_state"
description = "Namada ledger state"
resolver = "2"
authors.workspace = true
edition.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = []

# for integration tests and test utilities
testing = [
    "proptest",
    "namada_core/testing",
    "namada_merkle_tree/testing"
]
migrations = [
    "namada_migrations",
    "linkme",
]
benches = []

[dependencies]
namada_core = { path = "../core", default-features = false }
namada_events = { path = "../events", default-features = false }
namada_gas = { path = "../gas" }
namada_macros = { path = "../macros" }
namada_merkle_tree = { path = "../merkle_tree" }
namada_migrations = { path = "../migrations", optional = true }
namada_replay_protection = { path = "../replay_protection" }
namada_storage = { path = "../storage" }
namada_tx = { path = "../tx" }

borsh.workspace = true
clru.workspace = true
itertools.workspace = true
linkme = {workspace = true, optional = true}
smooth-operator.workspace = true
thiserror.workspace = true
tracing.workspace = true
patricia_tree.workspace = true
proptest = { workspace = true, optional = true }

[dev-dependencies]
namada_core = { path = "../core", features = ["testing"] }
namada_merkle_tree = { path = "../merkle_tree", features = ["testing"] }
namada_parameters = { path = "../parameters", features = ["testing"] }

assert_matches.workspace = true
chrono.workspace = true
pretty_assertions.workspace = true
proptest.workspace = true
test-log.workspace = true
