[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "namada_wasm_for_tests"
resolver = "2"
version = "0.30.0"

[lib]
crate-type = ["cdylib"]

# The features should be used individually to build the selected wasm.
# Newly added wasms should also be added into the Makefile `$(wasms)` list.
[features]
tx_memory_limit = []
tx_no_op = []
tx_fail = []
tx_read_storage_key = []
tx_write = []
vp_always_false = []
vp_always_true = []
vp_eval = []
vp_memory_limit = []
vp_read_storage_key = []
tx_proposal_code = []

[dependencies]
namada_test_utils = {path = "../../test_utils"}
namada_tx_prelude = {path = "../../tx_prelude"}
namada_vp_prelude = {path = "../../vp_prelude"}
wee_alloc = "0.4.5"
getrandom = { version = "0.2", features = ["custom"] }

[dev-dependencies]
namada_tests = {path = "../../tests"}

[profile.release]
# smaller and faster wasm https://rustwasm.github.io/book/reference/code-size.html#compiling-with-link-time-optimizations-lto
lto = true
# simply terminate on panics, no unwinding
panic = "abort"
