# Genesis balances.
#
# This files contains the genesis balances of any tokens present at genesis
# associated with implicit addresses (in the form of public keys) or established
# addresses.
#
# For example:
# ```
# [token.NAM]
# some_pk_bech32m_encoding = 10 # genesis tokens, the amount can have up to 6 decimal places
# ```
#
# The public keys present in here are taken from `pre-genesis/wallet.toml`.
# As for the established addresses, these are derived from their respective
# genesis tx toml files.

[token.NAM]
# albert
tnam1qxfj3sf6a0meahdu9t6znp05g8zx4dkjtgyn9gfu = "2000000"
tnam1qrr8r00nrf6490ff9zgfz52xrnfhdja7rqvldl46 = "2000000"
# bertha
tnam1q9rhgyv3ydq0zu3whnftvllqnvhvhm270qxay5tn = "2000000"
tnam1qqc2ge6tg7s03nlshjr5d79dqyjr33aa8g2mxyzm = "2000000"
# christel
tnam1q9sx4ekzqaq3xdxtruxkm764nhl00cvcsc7df5jf = "2000000"
tnam1qz0nvec686e9pks8ynhm5ddq8ke7j2eey50uagtr = "2000000"
# daewon
tnam1qpca48f45pdtpcz06rue7k4kfdcjrvrux5cr3pwn = "100000000"
# ester
tnam1qpm3dpsv76ttu382vfggtr7m8n00na3sfyzm2g2q = "1000000"
# validator-0
tnam1q9vhfdur7gadtwx4r223agpal0fvlqhywylf2mzx = "200000"
tnam1qrdrgx6d3rzl2f5yn6nde6wg20sl6kmtug3ecg7z = "200000"
# validator-0-account-key
tnam1qzwnw8rdyg8c5nrdwrcd87pgdxygr2eyguzy9c44 = "1000000"
<<<<<<< HEAD
=======
# frank
tnam1qx9ggvnemv8j3a7u92r7mktgfq45q4cj3vch6wmn = "2000000"
tnam1qq0345c0vr04wyjfkp0lfqkdp5n0t7ua4cswzkhm = "2000000"
>>>>>>> 52d0ebbd7c (Revert "ci: minors")

[token.BTC]
# albert
tnam1qxfj3sf6a0meahdu9t6znp05g8zx4dkjtgyn9gfu = "1000000"
# bertha
tnam1q9rhgyv3ydq0zu3whnftvllqnvhvhm270qxay5tn = "1000000"
# christel
tnam1q9sx4ekzqaq3xdxtruxkm764nhl00cvcsc7df5jf = "1000000"
# daewon-key
tnam1qpca48f45pdtpcz06rue7k4kfdcjrvrux5cr3pwn = "1000000"
# ester-key
tnam1qpm3dpsv76ttu382vfggtr7m8n00na3sfyzm2g2q = "1000000"
# validator-0
tnam1q9vhfdur7gadtwx4r223agpal0fvlqhywylf2mzx = "1000000"
<<<<<<< HEAD
=======
# frank
tnam1qx9ggvnemv8j3a7u92r7mktgfq45q4cj3vch6wmn = "1000000"
>>>>>>> 52d0ebbd7c (Revert "ci: minors")

[token.ETH]
# albert
tnam1qxfj3sf6a0meahdu9t6znp05g8zx4dkjtgyn9gfu = "1000000"
# bertha
tnam1q9rhgyv3ydq0zu3whnftvllqnvhvhm270qxay5tn = "1000000"
# christel
tnam1q9sx4ekzqaq3xdxtruxkm764nhl00cvcsc7df5jf = "1000000"
# daewon-key
tnam1qpca48f45pdtpcz06rue7k4kfdcjrvrux5cr3pwn = "1000000"
# ester-key
tnam1qpm3dpsv76ttu382vfggtr7m8n00na3sfyzm2g2q = "1000000"
# validator-0
tnam1q9vhfdur7gadtwx4r223agpal0fvlqhywylf2mzx = "1000000"
<<<<<<< HEAD
=======
# frank
tnam1qx9ggvnemv8j3a7u92r7mktgfq45q4cj3vch6wmn = "1000000"
>>>>>>> 52d0ebbd7c (Revert "ci: minors")


[token.DOT]
# albert
tnam1qxfj3sf6a0meahdu9t6znp05g8zx4dkjtgyn9gfu = "1000000"
# bertha
tnam1q9rhgyv3ydq0zu3whnftvllqnvhvhm270qxay5tn = "1000000"
# christel
tnam1q9sx4ekzqaq3xdxtruxkm764nhl00cvcsc7df5jf = "1000000"
# daewon-key
tnam1qpca48f45pdtpcz06rue7k4kfdcjrvrux5cr3pwn = "1000000"
# ester-key
tnam1qpm3dpsv76ttu382vfggtr7m8n00na3sfyzm2g2q = "1000000"
# validator-0
tnam1q9vhfdur7gadtwx4r223agpal0fvlqhywylf2mzx = "1000000"
<<<<<<< HEAD
=======
# frank
tnam1qx9ggvnemv8j3a7u92r7mktgfq45q4cj3vch6wmn = "1000000"
>>>>>>> 52d0ebbd7c (Revert "ci: minors")

[token.Schnitzel]
# albert
tnam1qxfj3sf6a0meahdu9t6znp05g8zx4dkjtgyn9gfu = "1000000"
# bertha
tnam1q9rhgyv3ydq0zu3whnftvllqnvhvhm270qxay5tn = "1000000"
# christel
tnam1q9sx4ekzqaq3xdxtruxkm764nhl00cvcsc7df5jf = "1000000"
# daewon-key
tnam1qpca48f45pdtpcz06rue7k4kfdcjrvrux5cr3pwn = "1000000"
# ester-key
tnam1qpm3dpsv76ttu382vfggtr7m8n00na3sfyzm2g2q = "1000000"
# validator-0
tnam1q9vhfdur7gadtwx4r223agpal0fvlqhywylf2mzx = "1000000"
<<<<<<< HEAD
=======
# frank
tnam1qx9ggvnemv8j3a7u92r7mktgfq45q4cj3vch6wmn = "1000000"
>>>>>>> 52d0ebbd7c (Revert "ci: minors")

[token.Apfel]
# albert
tnam1qxfj3sf6a0meahdu9t6znp05g8zx4dkjtgyn9gfu = "1000000"
# bertha
tnam1q9rhgyv3ydq0zu3whnftvllqnvhvhm270qxay5tn = "1000000"
# christel
tnam1q9sx4ekzqaq3xdxtruxkm764nhl00cvcsc7df5jf = "1000000"
# daewon-key
tnam1qpca48f45pdtpcz06rue7k4kfdcjrvrux5cr3pwn = "1000000"
# ester-key
tnam1qpm3dpsv76ttu382vfggtr7m8n00na3sfyzm2g2q = "1000000"
# validator-0
tnam1q9vhfdur7gadtwx4r223agpal0fvlqhywylf2mzx = "1000000"
<<<<<<< HEAD
=======
# frank
tnam1qx9ggvnemv8j3a7u92r7mktgfq45q4cj3vch6wmn = "1000000"
>>>>>>> 52d0ebbd7c (Revert "ci: minors")

[token.Kartoffel]
# albert
tnam1qxfj3sf6a0meahdu9t6znp05g8zx4dkjtgyn9gfu = "1000000"
# bertha
tnam1q9rhgyv3ydq0zu3whnftvllqnvhvhm270qxay5tn = "1000000"
# christel
tnam1q9sx4ekzqaq3xdxtruxkm764nhl00cvcsc7df5jf = "1000000"
# daewon-key
tnam1qpca48f45pdtpcz06rue7k4kfdcjrvrux5cr3pwn = "1000000"
# ester-key
tnam1qpm3dpsv76ttu382vfggtr7m8n00na3sfyzm2g2q = "1000000"
# validator-0
tnam1q9vhfdur7gadtwx4r223agpal0fvlqhywylf2mzx = "1000000"
<<<<<<< HEAD
=======
# frank
tnam1qx9ggvnemv8j3a7u92r7mktgfq45q4cj3vch6wmn = "1000000"
>>>>>>> 52d0ebbd7c (Revert "ci: minors")
