[parameters]
native_token = "NAM"
min_num_of_blocks = 4
max_expected_time_per_block = 30
max_tx_bytes = 1048576
max_proposal_bytes = 6291456
vp_allowlist = []
tx_allowlist = []
implicit_vp = "vp_implicit"
epochs_per_year = 105120
max_signatures_per_transaction = 15
max_block_gas = 20000000
fee_unshielding_gas_limit = 20000
fee_unshielding_descriptions_limit = 15

[pos_params]
max_validator_slots = 128
pipeline_len = 2
unbonding_len = 3
tm_votes_per_token = "1"
block_proposer_reward = "0.125"
block_vote_reward = "0.1"
max_inflation_rate = "0.1"
target_staked_ratio = "0.6667"
duplicate_vote_min_slash_rate = "0.001"
light_client_attack_min_slash_rate = "0.001"
cubic_slashing_window_length = 1
validator_stake_threshold = "1000000"
liveness_window_check = 100
liveness_threshold = "0.9"
rewards_gain_p = "0.25"
rewards_gain_d = "0.25"

[gov_params]
min_proposal_fund = 500
max_proposal_code_size = 600000
min_proposal_voting_period = 3
max_proposal_period = 27
max_proposal_content_size = 10000
min_proposal_grace_epochs = 6

[pgf_params]
stewards = [ "tnam1q9rhgyv3ydq0zu3whnftvllqnvhvhm270qxay5tn", "tnam1q9vhfdur7gadtwx4r223agpal0fvlqhywylf2mzx",]
pgf_inflation_rate = "0.1"
stewards_inflation_rate = "0.01"

[parameters.minimum_gas_price]
nam = "0.000001"
