# Transactions pasted from:
#
# 1. `src/pre-genesis/validator-0/transactions.toml`
# 2. `src/pre-genesis/signed-transactions.toml`

# 1.

[[validator_account]]
alias = "validator-0"
dkg_key = "dpktest1vqqqqqqndwmp3cvzfuepzvdh3fmt4dvjwd4vx6ffxk6t4vm6waysng2q8zh3yu8hdnxhwnwq22p8fwaqlyzcggef6k6qv3h3qtyy8c8c686w50v7d0z49ufd6zje46ujzc4ew5z7sdh45d94cvywy2v40yz9jlckh8cksr"
vp = "vp_validator"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "127.0.0.1:27656"

[validator_account.account_key]
pk = "pktest1qpqznlesv6fcgsz9x4rsn7l4dsnp7h5sswvs9atw0zgq3uwp0jll2r42szz"
authorization = "sigtest1qrcy6a095uj6n8ryc9fkfw3hn2jn285g82hdratzrvmg22xp5qdmyr7e9q97t77v4zr8a73x4c3k53pcec3mp4ugt5jqd2w0fvd7nhcp0ajsk4"

[validator_account.consensus_key]
pk = "pktest1qpk2a5m26cgnrp32l2c2hss03draxwnctu92llhlr6kjesn2kt892k2kklp"
authorization = "sigtest1qzajuey408zf66wgw8x3awd5jx9x249csx63n80clehj238qqpsf9cdr630edqjr8fw95vywlngy368r087sge2xy89qpcsrxvwtm3gr0h6g79"

[validator_account.protocol_key]
pk = "pktest1qpfv9pj4zmelcg98rtw8wezztzdgpuczuxjmx946klkxajmvvcxjz3vsv63"
authorization = "sigtest1qz0aerskgtzwmgxwgml72zyz4974njfz6s9dl7r399d0v64pzsmctkwe8f28dwyef52hklj6r2fqmeypncvv3qg2x4hg4u3g23kw23qt73uzmy"

[validator_account.tendermint_node_key]
pk = "pktest1qp7shxxfdkp8ft8xfkgf2vqy7u6effdp82w0cq6aq8575txul33t63dyd68"
authorization = "sigtest1qq87l6zjuswmrfeysxp8j0tu5zlklnswzaqgcuyaq23p49hhvupa57r3rwrh3txfuvq8lh5e7wu7d90js8cn7a7dygs7v5yx2a9ljtqxwl0chr"

[validator_account.eth_hot_key]
pk = "pktest1qypdzza7uqtklzzs50hhy07h5ru9p0v8y5666wwulqnd3mdpuj0tcxsgck694"
authorization = "sigtest1q9qtzvwlqhnft5jgeyms2w757dlly8rjg4g89593ayhan0fx7uvjzvm7r7ltgsly9tp6783pqpl6ezxty240udrrknxmunymz6lm523qqqwx72ra"

[validator_account.eth_cold_key]
pk = "pktest1qypzca0n6l890jc83nk5lljuzps04xmfccz3f87xc6ez40t2wvql48s52cx8r"
authorization = "sigtest1q8qmjstc2jtt3dwueepv0njk9te5qpj6z9yj6w0duhagswz80vyws3ywdsy9n49qnjecvnpxwlna3578vn423tgd4rrtss06ejgkj7c5qyv22nm6"

[[transfer]]
token = "nam"
source = "pktest1qzp22w6trhmxmp2dx5h883c2l684z0e20a9egusmxaat62wvaa4agcthpup"
target = "validator-0"
amount = "200000"
signature = "sigtest1qz8ch7n6jp7g7hvnzkhmprhqc5umd0gatarlttm7gpcdx6g8hmgqffdq67fn6vzcflmym5xej3m5jmfw7nap00s4nlx2zxrlwz0wlfgts9kera"

[[bond]]
source = "validator-0"
validator = "validator-0"
amount = "100000"
signature = "sigtest1qpss2x7vewnr2sr2wxj0ftldcmvv7v7t7qsr26k2l2hx4gls7y9sksrcq0m9vv2ymdqqxgmmw0dmuwazflxuqt4v2p2wng4endtcfcc0v6f6tj"

# 2.

[[established_account]]
alias = "faucet"
vp = "vp_testnet_faucet"

[established_account.public_key]
pk = "pktest1qzh2d8vk9wvj2j63fa3cvjru9uldpdjctjjxpafl5r8vwwf56pdgy2dpher"
authorization = "sigtest1qrp4gkkj297d79cw09ms4aleae2lkr452q75n8u5d6mmqus0jdl77mwp0mdpvslwdrvmppl6wqzyx743r93y9c2mfw3vdqv6khj6glqxxgktrv"

[[established_account]]
alias = "albert"
vp = "vp_user"

[established_account.public_key]
pk = "pktest1qz0aphcsrw37j8fy742cjwhphu9jwx7esd3ad4xxtxrkwv07ff63wnnul44"
authorization = "sigtest1qqljvm4244f764hm6mw4e49tz5csetyxu9r44cgjtdjlhc08pa3f7em6dwseav2rleuvcrfnnwv9xaqdjvq0ek6qmwmhyjqvpehlsksget58v0"

[[established_account]]
alias = "bertha"
vp = "vp_user"

[established_account.public_key]
pk = "pktest1qpyfnrl6qdqvguah9kknvp9t6ajcrec7fge56pcgaa655zkua3ndsl9tn4a"
authorization = "sigtest1qqfh5v2shrxe6f5qjczvykp3geen3kzq5haev4ryqlteppzeqf3jetstkn6l0zdw95w6kph4u9dx5gmlvtsyuw3c43jzcsf09feck3qf33zynh"

[[established_account]]
alias = "christel"
vp = "vp_user"

[established_account.public_key]
pk = "pktest1qp6uy52q0fldjxupznuskm69fkuswx3fq3vw9kekzp4enkh5h7pmzy242c2"
authorization = "sigtest1qrx0h0zxwl5rd4zqrk6heth4602xqek505gcd9g9wuau4yxkxarzy8hh32avaxg55guanqzdd76h8lcc9fkclzuukf4ay0a5euwk32ggn0akrn"

[[transfer]]
token = "nam"
source = "pktest1qzh2d8vk9wvj2j63fa3cvjru9uldpdjctjjxpafl5r8vwwf56pdgy2dpher"
target = "faucet"
amount = "9123372036854"
signature = "sigtest1qpldws3c6culv3sen396u6l977gw0lngp034d7h9nyrxf20t7h9tx8jp0rrk8aamc4lhkgvqgpzeyg8twh6748qympqgjgc0cfzmvscwm8eacd"

[[transfer]]
token = "btc"
source = "pktest1qzh2d8vk9wvj2j63fa3cvjru9uldpdjctjjxpafl5r8vwwf56pdgy2dpher"
target = "faucet"
amount = "9123372036854"
signature = "sigtest1qzlp29ylc0j2ad6vj7jmgtanvv94e2nyj9mynpzjsk5cfps0k7q7z72364dh7axn2tlssxchfth9gqrh9ap77aml7x3el6y6hahwdvgpwpe88r"

[[transfer]]
token = "dot"
source = "pktest1qzh2d8vk9wvj2j63fa3cvjru9uldpdjctjjxpafl5r8vwwf56pdgy2dpher"
target = "faucet"
amount = "9123372036854"
signature = "sigtest1qreejkvm6czr5wrnza6mcefryhzqr8n4zeke6xlmrku7hdrkhmp9sdwk7uhmn68dvm8wyj8vdmlv6k5g0uh4xq4800t2ha945sn3zccpe3zep2"

[[transfer]]
token = "schnitzel"
source = "pktest1qzh2d8vk9wvj2j63fa3cvjru9uldpdjctjjxpafl5r8vwwf56pdgy2dpher"
target = "faucet"
amount = "9123372036854"
signature = "sigtest1qp5y3ms707ky7kvtgjvx5szpz2c5pscakhtszpvd0vzvf68x0gll6wx8mgtvrjqp2hap5v7wcge3lue86dm8755g7y9nphy92nksj2c0fqquwz"

[[transfer]]
token = "apfel"
source = "pktest1qzh2d8vk9wvj2j63fa3cvjru9uldpdjctjjxpafl5r8vwwf56pdgy2dpher"
target = "faucet"
amount = "9123372036854"
signature = "sigtest1qqh4vvdukv5e2ujznpau2vlwfr8hljashemah5v92tju204u79vj06mxtnqmmtlfm5734wufud67kuykdxy8ecjx7gn0jsesqze304qf5df90j"

[[transfer]]
token = "kartoffel"
source = "pktest1qzh2d8vk9wvj2j63fa3cvjru9uldpdjctjjxpafl5r8vwwf56pdgy2dpher"
target = "faucet"
amount = "9123372036854"
signature = "sigtest1qqf9kr8unfrf4jzgpa2danu6jg3d40ssu6majaen77lp3v7mn5f98e9rkra73mjpxzke94d4zqjht6qlcj5f27xw6grc2pnz9xg6ddcfkdc8cn"

[[transfer]]
token = "nam"
source = "pktest1qz0aphcsrw37j8fy742cjwhphu9jwx7esd3ad4xxtxrkwv07ff63wnnul44"
target = "albert"
amount = "1000000"
signature = "sigtest1qrxfthuz5yzapdt82d8nc656ffrzkxnkfg6fw8w7e6045vcpn8kpr4c536ug4fs2ddz5823dfd3w4qnhcl40qmtasfccaa99a0hvjcqvyy2l02"

[[transfer]]
token = "btc"
source = "pktest1qz0aphcsrw37j8fy742cjwhphu9jwx7esd3ad4xxtxrkwv07ff63wnnul44"
target = "albert"
amount = "1000000"
signature = "sigtest1qq826qel8zn5p4dfx25ma45uxeskx0yjlsaxp38uyvehvds6t93c8wkhaydunm4nzz9750dwhkjst00mfrwmu066y3rj6gtk5wjskxq9zvk7ed"

[[transfer]]
token = "eth"
source = "pktest1qz0aphcsrw37j8fy742cjwhphu9jwx7esd3ad4xxtxrkwv07ff63wnnul44"
target = "albert"
amount = "1000000"
signature = "sigtest1qzghddk0u6kpqaxhskrj8ah69d3hce95wndgvlpuyvuw0h0fnyrnp026ltvtfmfhpzywkf88yyhv80hzkus57s9nn6vn3ljvmkkf7zgq2nzn40"

[[transfer]]
token = "dot"
source = "pktest1qz0aphcsrw37j8fy742cjwhphu9jwx7esd3ad4xxtxrkwv07ff63wnnul44"
target = "albert"
amount = "1000000"
signature = "sigtest1qqlu8kajh0up5zhewd2h44fhq7zdaapqt9xaj8xp7jmdqpv4dl9d5tesw3wyr9su962rvpkf02x27579vqjk4f4advx7t9ejz74cjrc25puna6"

[[transfer]]
token = "schnitzel"
source = "pktest1qz0aphcsrw37j8fy742cjwhphu9jwx7esd3ad4xxtxrkwv07ff63wnnul44"
target = "albert"
amount = "1000000"
signature = "sigtest1qpukdd6f7pvtgau9v58xxwrnmv5pjra6527aggce9j8cu6fnekzag2cmmf4w0x0cn76gpth2vw6zcsnw37xjuz96hflqfnk5sznxe6cfd5mjnv"

[[transfer]]
token = "apfel"
source = "pktest1qz0aphcsrw37j8fy742cjwhphu9jwx7esd3ad4xxtxrkwv07ff63wnnul44"
target = "albert"
amount = "1000000"
signature = "sigtest1qprnsyhlruvw4a6jjs98xdd04gxdsgycywzt79gyyak68gn4f50ppdvdm0q6ns44cheu7s43kal0qsldml8s0zexqk3s9zmglu4l6fszwcqswy"

[[transfer]]
token = "nam"
source = "pktest1qpyfnrl6qdqvguah9kknvp9t6ajcrec7fge56pcgaa655zkua3ndsl9tn4a"
target = "bertha"
amount = "1000000"
signature = "sigtest1qpe3ms76cxvqsa58624ked5ndjr3jr3u7lf9ypalxdh29gajwmsxtzjxzswk0xmza90u47tgksr0d7enpd730ps7fq5u76l7ekxeyvgfnl0qxj"

[[transfer]]
token = "btc"
source = "pktest1qpyfnrl6qdqvguah9kknvp9t6ajcrec7fge56pcgaa655zkua3ndsl9tn4a"
target = "bertha"
amount = "1000000"
signature = "sigtest1qqq4yc6s3h4ysezcmgsdgyfsqu8mmrwwc8a358sm864zehx74ums8fmgmkyyr3wz9qqrc5fagwrw0a4mgqkkleumc0u6ynshj5ns0tcdrygupg"

[[transfer]]
token = "eth"
source = "pktest1qpyfnrl6qdqvguah9kknvp9t6ajcrec7fge56pcgaa655zkua3ndsl9tn4a"
target = "bertha"
amount = "1000000"
signature = "sigtest1qzyqkdxt3cxf0huv0hzskqmuthw38s3kj2sx50znzc68gzx64hrd3hkyx0g27pruwa9fv42suw3k8gkfaelcp4ymnvfw7ltx0mz2z9qr2lwwcs"

[[transfer]]
token = "nam"
source = "pktest1qp6uy52q0fldjxupznuskm69fkuswx3fq3vw9kekzp4enkh5h7pmzy242c2"
target = "christel"
amount = "1000000"
signature = "sigtest1qran2jh0dwuwchh45snhk3p9uyxqym57eg527pcjeekwhvpr5j0fy6dte7x3v2dwwc6vqmv49drpvmk6uhzlt2p8rqx0th3h7smf8rqrcpfxc7"

[[transfer]]
token = "btc"
source = "pktest1qp6uy52q0fldjxupznuskm69fkuswx3fq3vw9kekzp4enkh5h7pmzy242c2"
target = "christel"
amount = "1000000"
signature = "sigtest1qrxp6p56qtvsyp7jfs4jru3mkfv6l4t7hpguur72579pqjaexdry9turgmzwzj6qmua3s2y2a4krtuxwaag66j4dpz44aaqksy30tfcxmnhw2k"

[[transfer]]
token = "eth"
source = "pktest1qp6uy52q0fldjxupznuskm69fkuswx3fq3vw9kekzp4enkh5h7pmzy242c2"
target = "christel"
amount = "1000000"
signature = "sigtest1qrtrec6mps9p7zhmm7sywxwc7zdm32umt0zdwpuflrkh6952rx74amnsf9hn0yughs4e6czgpdmwsmujvkr4ptk2x24vtc8phz0s2asvtyy9pf"

[[bond]]
source = "albert"
validator = "validator-0"
amount = "20000"
signature = "sigtest1qpx0kc8rl966vnnswfwhcwxh5vv69p7lev2apc2yephag978gqg5903kuw6dugg9c6pg5jdw048umk72ntympphz0dka74aspldslaqr3q7eqr"
