# WASM Validity predicate that can be used for genesis accounts

# Implicit VP
[wasm.vp_implicit]
filename = "vp_implicit.wasm"

# Default user VP in established accounts
[wasm.vp_user]
filename = "vp_user.wasm"

# Default validator VP
[wasm.vp_validator]
filename = "vp_validator.wasm"

# MASP VP
[wasm.vp_masp]
filename = "vp_masp.wasm"
