# Genesis configuration source for E2E tests with:
# - 1 genesis validator
# - User accounts same as the ones in "dev" build (Albert, Bertha, Christel)

genesis_time = "2021-09-30T10:00:00Z"
native_token = "NAM"
faucet_pow_difficulty = 1
faucet_withdrawal_limit = "1_000"

[validator.validator-0]
# Validator's staked NAM at genesis.
tokens = 200000
# Amount of the validator's genesis token balance which is not staked.
non_staked_balance = 1000000000000
# VP for the validator account
validator_vp = "vp_validator"
# Commission rate for rewards
commission_rate = 0.05
# Maximum change per epoch in the commission rate
max_commission_rate_change = 0.01
# Public IP:port address.
# We set the port to be the default+1000, so that if a local node was running at 
# the same time as the E2E tests, it wouldn't affect them.
net_address = "127.0.0.1:27656"

# Some tokens present at genesis.

[token.NAM]
address = "atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5"
vp = "vp_token"
[token.NAM.balances]
Albert = 1000000
"Albert.public_key" = 100
Bertha = 1000000
"Bertha.public_key" = 2000
Christel = 1000000
"Christel.public_key" = 100
Daewon = 1000000
faucet = 9223372036
"faucet.public_key" = 100
"validator-0.public_key" = 100

[token.BTC]
address = "atest1v4ehgw36xdzryve5gsc52veeg5cnsv2yx5eygvp38qcrvd29xy6rys6p8yc5xvp4xfpy2v694wgwcp"
vp = "vp_token"
[token.BTC.balances]
Albert = 1000000
Bertha = 1000000
Christel = 1000000
Daewon = 1000000
faucet = 9223372036854

[token.ETH]
address = "atest1v4ehgw36xqmr2d3nx3ryvd2xxgmrq33j8qcns33sxezrgv6zxdzrydjrxveygd2yxumrsdpsf9jc2p"
vp = "vp_token"
[token.ETH.balances]
Albert = 1000000
Bertha = 1000000
Christel = 1000000
Daewon = 1000000
faucet = 9223372036854

[token.DOT]
address = "atest1v4ehgw36gg6nvs2zgfpyxsfjgc65yv6pxy6nwwfsxgungdzrggeyzv35gveyxsjyxymyz335hur2jn"
vp = "vp_token"
[token.Dot.balances]
Albert = 1000000
Bertha = 1000000
Christel = 1000000
Daewon = 1000000
faucet = 9223372036854

[token.Schnitzel]
address = "atest1v4ehgw36xue5xvf5xvuyzvpjx5un2v3k8qeyvd3cxdqns32p89rrxd6xx9zngvpegccnzs699rdnnt"
vp = "vp_token"
[token.Schnitzel.balances]
Albert = 1000000
Bertha = 1000000
Christel = 1000000
Daewon = 1000000
faucet = 9223372036854

[token.Apfel]
address = "atest1v4ehgw36gfryydj9g3p5zv3kg9znyd358ycnzsfcggc5gvecgc6ygs2rxv6ry3zpg4zrwdfeumqcz9"
vp = "vp_token"
[token.Apfel.balances]
Albert = 1000000
Bertha = 1000000
Christel = 1000000
Daewon = 1000000
faucet = 9223372036854

[token.Kartoffel]
address = "atest1v4ehgw36gep5ysecxq6nyv3jg3zygv3e89qn2vp48pryxsf4xpznvve5gvmy23fs89pryvf5a6ht90"
public_key = ""
vp = "vp_token"
[token.Kartoffel.balances]
Albert = 1000000
Bertha = 1000000
Christel = 1000000
Daewon = 1000000
faucet = 9223372036854

# Some established accounts present at genesis.
[established.faucet]
vp = "vp_testnet_faucet"

[established.Albert]
vp = "vp_user"

[established.Bertha]
vp = "vp_user"

[established.Christel]
vp = "vp_user"

[established.masp]
address = "atest1v4ehgw36xaryysfsx5unvve4g5my2vjz89p52sjxxgenzd348yuyyv3hg3pnjs35g5unvde4ca36y5"
vp = "vp_masp"

[implicit.Daewon]

# Wasm VP definitions

# Implicit VP
[wasm.vp_implicit]
filename = "vp_implicit.wasm"

# Default user VP in established accounts
[wasm.vp_user]
filename = "vp_user.wasm"

# Default validator VP
[wasm.vp_validator]
# filename (relative to wasm path used by the node)
filename = "vp_validator.wasm"

# Token VP
[wasm.vp_token]
filename = "vp_token.wasm"

# Faucet VP
[wasm.vp_testnet_faucet]
filename = "vp_testnet_faucet.wasm"

# MASP VP
[wasm.vp_masp]
filename = "vp_masp.wasm"

# General protocol parameters.
[parameters]
# Minimum number of blocks in an epoch.
min_num_of_blocks = 4
# Maximum expected time per block (in seconds).
max_expected_time_per_block = 30
# Max payload size, in bytes, for a tx batch proposal.
max_proposal_bytes = 22020096
# vp whitelist
vp_whitelist = []
# tx whitelist
tx_whitelist = []
# Implicit VP WASM name
implicit_vp = "vp_implicit"
# Expected number of epochs per year (also sets the min duration of an epoch in seconds)
epochs_per_year = 31_536_000
# The P gain factor in the Proof of Stake rewards controller
pos_gain_p = 0.1
# The D gain factor in the Proof of Stake rewards controller
pos_gain_d = 0.1

# Proof of stake parameters.
[pos_params]
# Maximum number of consensus validators.
max_validator_slots = 128
# Pipeline length (in epochs). Any change in the validator set made in
# epoch 'n' will become active in epoch 'n + pipeline_len'.
pipeline_len = 2
# Unbonding length (in epochs). Validators may have their stake slashed
# for a fault in epoch 'n' up through epoch 'n + unbonding_len'.
unbonding_len = 3
# Votes per fundamental staking token (namnam)
tm_votes_per_token = 1
# Reward for proposing a block.
block_proposer_reward = 0.125
# Reward for voting on a block.
block_vote_reward = 0.1
# Maximum inflation rate per annum (10%)
max_inflation_rate = 0.1
# Targeted ratio of staked tokens to total tokens in the supply
target_staked_ratio = 0.6667
# Portion of a validator's stake that should be slashed on a duplicate
# vote.
duplicate_vote_min_slash_rate = 0.001
# Portion of a validator's stake that should be slashed on a light
# client attack.
light_client_attack_min_slash_rate = 0.001

# Governance parameters.
[gov_params]
# minimum amount of nam token to lock
min_proposal_fund = 500
# proposal code size in bytes
max_proposal_code_size = 300000
# min proposal period length in epochs
min_proposal_period = 3
# max proposal period length in epochs
max_proposal_period = 27
# maximum number of characters in the proposal content
max_proposal_content_size = 10000
# minimum epochs between end and grace epoch
min_proposal_grace_epochs = 6
