# Token accounts with their validity predicates

[token.NAM]
vp = "vp_token"
denom = 6

[token.NAM.masp_params]
max_reward_rate = "0.01"
kd_gain_nom = "0.25"
kp_gain_nom = "0.25"
locked_amount_target = 10000
