[package]
name = "tx_write"
description = "Wasm transaction used for testing."
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
namada_test_utils.workspace = true
namada_tx_prelude.workspace = true
rlsf.workspace = true
getrandom.workspace = true

[dev-dependencies]
namada_tests = { path = "../../crates/tests" }

proptest = "1.4.0"
test-log = {version = "0.2.14", default-features = false, features = ["trace"]}
tracing = "0.1.30"
tracing-subscriber = {version = "0.3.7", default-features = false, features = ["env-filter", "fmt"]}

[lib]
crate-type = ["cdylib"]
