[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "namada_tx_prelude"
resolver = "2"
version = "0.12.0"

[features]
default = ["abciplus"]
abciplus = [
  "namada_core/abciplus",
  "namada_proof_of_stake/abciplus",
  "namada_vm_env/abciplus",
]

[dependencies]
masp_primitives = { git = "https://github.com/anoma/masp", rev = "bee40fc465f6afbd10558d12fe96eb1742eee45c" }
namada_core = {path = "../core", default-features = false}
namada_macros = {path = "../macros"}
namada_proof_of_stake = {path = "../proof_of_stake", default-features = false}
namada_vm_env = {path = "../vm_env", default-features = false}
borsh = "0.9.0"
sha2 = "0.10.1"
thiserror = "1.0.30"
rust_decimal = "1.26.1"
