[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "anoma_tx_prelude"
resolver = "2"
version = "0.6.1"

[features]
default = ["ABCI"]

ABCI = [
  "anoma_vm_env/ABCI",
]

ABCI-plus-plus = [
  "anoma_vm_env/ABCI-plus-plus",
]

[dependencies]
anoma_vm_env = {path = "../vm_env", default-features = false}
sha2 = "0.10.1"
