[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "namada_tx_prelude"
resolver = "2"
version = "0.7.1"

[features]
default = []

[dependencies]
namada_vm_env = {path = "../vm_env"}
sha2 = "0.10.1"
