[package]
name = "tx_init_account"
description = "WASM transaction to initialize an account"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
namada_tx_prelude.workspace = true

rlsf.workspace = true
getrandom.workspace = true

[lib]
crate-type = ["cdylib"]
