[[established_account]]
vp = "vp_user"
threshold = 1
<<<<<<< HEAD
=======
public_keys = ["tpknam1qz0vuxgzsz5lu7peghyr4yx5tuexecm27hdgglkpe444v6nmy6d8yuxhn0r"]

[[established_account]]
vp = "vp_user"
threshold = 1
>>>>>>> 52d0ebbd7c (Revert "ci: minors")
public_keys = ["tpknam1qqwfpuvn8x7yqtquejhppef4vddv9ghusec2rkaxav38amamxaxpgj9cs79"]

[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qq52dx5e290wyh7ngdt6wudtyd502lg6ln49yvg3vz97e8j2ruux5e3yewq"]

[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qrnw8mxyqlj60mykgevnldcj5mg2fya7fs5a8xqdkd2gwtxhef0zy8a2wha"]

[[bond]]
source = "tnam1qxfj3sf6a0meahdu9t6znp05g8zx4dkjtgyn9gfu"
validator = "tnam1q9vhfdur7gadtwx4r223agpal0fvlqhywylf2mzx"
amount = "20000"

[bond.signatures]
tpknam1qrnw8mxyqlj60mykgevnldcj5mg2fya7fs5a8xqdkd2gwtxhef0zy8a2wha = "signam1qqp5p6k7g384x6gu65hzv9dve8fwftv02h4p3sgtwvz8vzgwjkr6cflxdv2kx7nrtxqha0mmpcmjeclrjwnlt7fphj4ugxsludlmt8qfs3k9q0"
