# This file contains hand-written unsigned transactions for localnet with:
#
# - 3 established accounts for "Albert", "Bertha" and "Christel"
# - a bond from "Albert"'s established account to validator-0
#
# Note that 1 localnet user account "Daewon" is left as
# implicit account, so their tokens are kept in the accounts derived from their
# keys used in `balances.toml`.
#
# This file is used to produce `signed-transactions.toml` with
# the `sign-genesis-txs` command.

# Albert
[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qrnw8mxyqlj60mykgevnldcj5mg2fya7fs5a8xqdkd2gwtxhef0zy8a2wha"]

# Bertha
[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qq52dx5e290wyh7ngdt6wudtyd502lg6ln49yvg3vz97e8j2ruux5e3yewq"]

# Christel
[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qqwfpuvn8x7yqtquejhppef4vddv9ghusec2rkaxav38amamxaxpgj9cs79"]

##########################################################################################

# Albert bonds to `validator-0`
[[bond]]
source = "tnam1qxfj3sf6a0meahdu9t6znp05g8zx4dkjtgyn9gfu"
validator = "tnam1q9vhfdur7gadtwx4r223agpal0fvlqhywylf2mzx"
amount = "20000"
