[view_keys]

[spend_keys]

[payment_addrs]

[secret_keys]
albert-key = "unencrypted:0083318ccceac6c08a0177667840b4b93f0e455e45d4c38c28b73b8f8462fbf548"
bertha-key = "unencrypted:0073ed61817720d27784e7a9bca4a60668d763a6f7ecac2d45ed1f241aa5c59e99"
christel-key = "unencrypted:003625b939a58ef60402d7cf8fc04250026cc1ba90cc3028af1ce6b22be857ffc7"
daewon = "unencrypted:00d19e226c0e7d123d79f5908b5948d4c461b66a5f8aa95600c28b55ab6f5dc772"
ester = "unencrypted:01369093e2035d84f72a7e5a17c89b7a938b5d08cc87b2289805e3afcc66ef9a42"
faucet-key = "unencrypted:00548aa8393422b88dce5f4be8ee0320638061c3e0649ada1b0dacbec4c0c75bb2"
validator-0-balance-key = "unencrypted:000b9c8cb8f3ad6b8a387b064a11c0e98189814e9733aa7bb1e802425f6356f98a"

[public_keys]
albert-key = "ED25519_PK_PREFIXpktest1qz0aphcsrw37j8fy742cjwhphu9jwx7esd3ad4xxtxrkwv07ff63wnnul44"
bertha-key = "ED25519_PK_PREFIXpktest1qpyfnrl6qdqvguah9kknvp9t6ajcrec7fge56pcgaa655zkua3ndsl9tn4a"
christel-key = "ED25519_PK_PREFIXpktest1qp6uy52q0fldjxupznuskm69fkuswx3fq3vw9kekzp4enkh5h7pmzy242c2"
daewon = "ED25519_PK_PREFIXpktest1qzz4x4fammhdcfa0g8xw4udkq8s4n6kjhzlxh00ul3da05wuu9wkyuzdckd"
ester = "SECP256K1_PK_PREFIXpktest1qypvqpzu74nafjahlwyq272dj76qq9rz30dulyc94883tmj893mquqsafsprd"
faucet-key = "ED25519_PK_PREFIXpktest1qzh2d8vk9wvj2j63fa3cvjru9uldpdjctjjxpafl5r8vwwf56pdgy2dpher"
validator-0-balance-key = "ED25519_PK_PREFIXpktest1qzp22w6trhmxmp2dx5h883c2l684z0e20a9egusmxaat62wvaa4agcthpup"

[derivation_paths]

[addresses]
albert-key = "tnam1qp2yqaffsk2wekd8fheu5c0cv3heg8v37vmdd45u"
bertha-key = "tnam1qqm6sgr63e2zgngh5hlff8r8rennq4vldgdyqdaa"
christel-key = "tnam1qrcgykypppxwx96zkejvhjnda7mn9m3prsz78pkf"
daewon = "tnam1qpca48f45pdtpcz06rue7k4kfdcjrvrux5cr3pwn"
ester = "tnam1qpm3dpsv76ttu382vfggtr7m8n00na3sfyzm2g2q"
faucet-key = "tnam1qzgcl2znamndmku7ujw6e79dmvd4v7rfd5c89dfz"
validator-0-balance-key = "tnam1qrarncdv96reutgdetkwewdpdyncykaflyzz36vh"

[pkhs]
37A8207A8E54244D17A5FE949C671E6730559F6A = "bertha-key"
544075298594ECD9A74DF3CA61F8646F941D91F3 = "albert-key"
71DA9D35A05AB0E04FD0F99F5AB64B7121B07C35 = "daewon"
918FA853EEE6DDDB9EE49DACF8ADDB1B5678696D = "faucet-key"
F0825881084CE31742B664CBCA6DEFB732EE211C = "christel-key"
7716860CF696BE44EA6250858FDB3CDEF9F63049 = "ester"
FA39E1AC2E879E2D0DCAECECB9A16927825BA9F9 = "validator-0-balance-key"

[address_vp_types]
