[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "vp_template"
resolver = "2"
version = "0.9.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
namada_vp_prelude = {path = "../../vp_prelude"}
borsh = "0.9.0"
wee_alloc = "0.4.5"
getrandom = { version = "0.2", features = ["custom"] }

[dev-dependencies]
namada_tests = {path = "../../tests"}
