[package]
name = "namada_macros"
description = "Namada macros"
resolver = "2"
authors.workspace = true
edition.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lib]
proc-macro = true

[features]
migrations = ["namada_migrations/migrations"]

[dependencies]
namada_migrations = {path = "../migrations"}
paste.workspace = true
proc-macro2 = "1.0"
quote = "1.0"
syn = {version="1.0", features = ["full", "extra-traits"]}
sha2.workspace = true
lazy_static = "1.4.0"

[dev-dependencies]
pretty_assertions.workspace = true
