[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "namada_wasm"
resolver = "2"
version = "0.31.9"

[lib]
crate-type = ["cdylib"]

# The features should be used individually to build the selected wasm.
# Newly added wasms should also be added into the Makefile `$(wasms)` list.
[features]
tx_bond = ["namada_tx_prelude"]
tx_bridge_pool = ["namada_tx_prelude"]
tx_change_validator_commission = ["namada_tx_prelude"]
tx_change_consensus_key = ["namada_tx_prelude"]
tx_change_validator_metadata = ["namada_tx_prelude"]
tx_claim_rewards = ["namada_tx_prelude"]
tx_deactivate_validator = ["namada_tx_prelude"]
tx_from_intent = ["namada_tx_prelude"]
tx_ibc = ["namada_tx_prelude"]
tx_init_account = ["namada_tx_prelude"]
tx_init_proposal = ["namada_tx_prelude"]
tx_become_validator = ["namada_tx_prelude"]
tx_reactivate_validator = ["namada_tx_prelude"]
tx_redelegate = ["namada_tx_prelude"]
tx_reveal_pk = ["namada_tx_prelude"]
tx_transfer = ["namada_tx_prelude"]
tx_unbond = ["namada_tx_prelude"]
tx_unjail_validator = ["namada_tx_prelude"]
tx_update_account = ["namada_tx_prelude"]
tx_vote_proposal = ["namada_tx_prelude"]
tx_withdraw = ["namada_tx_prelude"]
tx_update_steward_commission = ["namada_tx_prelude"]
tx_resign_steward = ["namada_tx_prelude"]
vp_implicit = ["namada_vp_prelude", "once_cell"]
vp_user = ["namada_vp_prelude", "once_cell"]

[dependencies]
namada_tx_prelude = {path = "../../crates/tx_prelude", optional = true}
namada_vp_prelude = {path = "../../crates/vp_prelude", optional = true}

once_cell = {version = "1.8.0", optional = true}
wee_alloc = "0.4.5"
getrandom = { version = "0.2", features = ["custom"] }

[dev-dependencies]
namada = {path = "../../crates/namada"}
namada_tests = {path = "../../crates/tests"}
namada_test_utils = {path = "../../crates/test_utils"}
namada_tx_prelude = {path = "../../crates/tx_prelude"}
namada_vp_prelude = {path = "../../crates/vp_prelude"}

proptest = "1.4.0"
test-log = {version = "0.2.14", default-features = false, features = ["trace"]}
tracing = "0.1.30"
tracing-subscriber = {version = "0.3.7", default-features = false, features = ["env-filter", "fmt"]}
