[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "anoma_wasm"
resolver = "2"
version = "0.3.0"

[lib]
crate-type = ["cdylib"]

# The features should be used individually to build the selected wasm.
# Newly added wasms should also be added into the Makefile `$(wasms)` list.
[features]
tx_bond = []
tx_from_intent = []
tx_init_account = []
tx_init_validator = []
tx_transfer = []
tx_unbond = []
tx_update_vp = []
tx_withdraw = []
vp_testnet_faucet = ["once_cell"]
vp_token = []
vp_user = ["once_cell", "rust_decimal"]

[dependencies]
anoma_tx_prelude = {path = "../../tx_prelude"}
anoma_vm_env = {path = "../../vm_env"}
anoma_vp_prelude = {path = "../../vp_prelude"}
borsh = "0.9.0"
once_cell = {version = "1.8.0", optional = true}
rust_decimal = {version = "1.14.3", optional = true}
wee_alloc = "0.4.5"

[dev-dependencies]
anoma_tests = {path = "../../tests"}
proptest = "1.0.0"
tracing = "0.1.29"
tracing-subscriber = {version = "0.2.25", default-features = false, features = ["env-filter", "fmt"]}

[patch.crates-io]
tendermint = {git = "https://github.com/heliaxdev/tendermint-rs", branch = "yuji/rebase_v0.23.0"}
tendermint-light-client = {git = "https://github.com/heliaxdev/tendermint-rs", branch = "yuji/rebase_v0.23.0"}
tendermint-proto = {git = "https://github.com/heliaxdev/tendermint-rs", branch = "yuji/rebase_v0.23.0"}
tendermint-rpc = {git = "https://github.com/heliaxdev/tendermint-rs", branch = "yuji/rebase_v0.23.0"}
tendermint-testgen = {git = "https://github.com/heliaxdev/tendermint-rs", branch = "yuji/rebase_v0.23.0"}

[profile.release]
# smaller and faster wasm (https://rustwasm.github.io/book/reference/code-size.html#compiling-with-link-time-optimizations-lto)
lto = true
# simply terminate on panics, no unwinding
panic = "abort"
# tell llvm to optimize for size (https://rustwasm.github.io/book/reference/code-size.html#tell-llvm-to-optimize-for-size-instead-of-speed)
opt-level = 'z'
