[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "anoma_wasm"
resolver = "2"
version = "0.6.1"

[lib]
crate-type = ["cdylib"]

# The features should be used individually to build the selected wasm.
# Newly added wasms should also be added into the Makefile `$(wasms)` list.
[features]
tx_bond = ["anoma_tx_prelude"]
tx_from_intent = ["anoma_tx_prelude"]
tx_ibc = ["anoma_tx_prelude"]
tx_init_account = ["anoma_tx_prelude"]
tx_init_nft = ["anoma_tx_prelude"]
tx_init_proposal = ["anoma_tx_prelude"]
tx_init_validator = ["anoma_tx_prelude"]
tx_mint_nft = ["anoma_tx_prelude"]
tx_transfer = ["anoma_tx_prelude"]
tx_unbond = ["anoma_tx_prelude"]
tx_update_vp = ["anoma_tx_prelude"]
tx_vote_proposal = ["anoma_tx_prelude"]
tx_withdraw = ["anoma_tx_prelude"]
vp_nft = ["anoma_vp_prelude"]
vp_testnet_faucet = ["anoma_vp_prelude", "once_cell"]
vp_token = ["anoma_vp_prelude"]
vp_user = ["anoma_vp_prelude", "once_cell", "rust_decimal"]

[dependencies]
anoma_tx_prelude = {path = "../../tx_prelude", optional = true}
anoma_vp_prelude = {path = "../../vp_prelude", optional = true}
borsh = "0.9.0"
once_cell = {version = "1.8.0", optional = true}
rust_decimal = {version = "1.14.3", optional = true}
wee_alloc = "0.4.5"
getrandom = { version = "0.2", features = ["custom"] }

[dev-dependencies]
anoma = {path = "../../shared"}
anoma_tests = {path = "../../tests"}
anoma_tx_prelude = {path = "../../tx_prelude"}
anoma_vp_prelude = {path = "../../vp_prelude"}
# A fork with state machine testing
proptest = {git = "https://github.com/heliaxdev/proptest", branch = "tomas/sm"}
tracing = "0.1.30"
tracing-subscriber = {version = "0.3.7", default-features = false, features = ["env-filter", "fmt"]}
