[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2018"
license = "GPL-3.0"
name = "anoma_wasm"
resolver = "2"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

# The features should be used individually to build the selected wasm.
# Newly added wasms should also be added into the Makefile `$(wasms)` list.
[features]
mm_filter_token_exch = []
mm_token_exch = ["petgraph", "serde", "serde_json", "good_lp", "rust_decimal"]
tx_bond = []
tx_init_account = []
tx_from_intent = []
tx_transfer = []
tx_unbond = []
tx_update_vp = []
tx_withdraw = []
vp_testnet_faucet = ["once_cell"]
vp_token = []
vp_user = ["once_cell", "rust_decimal"]

[dependencies]
anoma_vm_env = {path = "../../vm_env"}
borsh = "0.9.0"
petgraph = {version = "0.5.1", features = ["serde-1"], optional = true}
serde = {version = "1.0.125", optional = true}
serde_json = {version = "1.0.64", optional = true}
wee_alloc = "0.4.5"
rust_decimal = { version = "1.14.3", optional = true }
good_lp = { version = "*", features = ["minilp"], default-features = false, optional = true }
once_cell = { version = "1.8.0", optional = true }

[dev-dependencies]
anoma_tests = {path = "../../tests"}
proptest = "1.0.0"
tracing = "0.1.26"
tracing-subscriber = {version = "0.2.18", default-features = false, features = ["env-filter", "fmt"]}

[profile.release]
# smaller and faster wasm (https://rustwasm.github.io/book/reference/code-size.html#compiling-with-link-time-optimizations-lto)
lto = true
# simply terminate on panics, no unwinding
panic = "abort"
# tell llvm to optimize for size (https://rustwasm.github.io/book/reference/code-size.html#tell-llvm-to-optimize-for-size-instead-of-speed)
opt-level = 'z'
