[package]
name = "namada_light_sdk"
description = "A higher level, user friendly version of the Namada SDK"
resolver = "2"
authors.workspace = true
edition.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
blocking = ["tokio"]
namada-eth-bridge = ["namada_sdk/namada-eth-bridge"]

[dependencies]
namada_sdk.workspace = true

borsh.workspace = true
prost.workspace = true
tendermint-config.workspace = true
tendermint-rpc = { workspace = true, features = ["http-client"] }
tokio = { workspace = true, features = ["rt"], optional = true }
serde_json = "1.0.108"
