[package]
name = "namada_apps"
description = "Namada CLI apps"
resolver = "2"
default-run = "namada"
authors.workspace = true
edition.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

# Namada CLI that aggregates some common commands for the node and the client
[[bin]]
doc = false
name = "namada"
path = "src/bin/namada/main.rs"

# Namada node
[[bin]]
doc = false
name = "namadan"
path = "src/bin/namada-node/main.rs"

# Namada client
[[bin]]
doc = false
name = "namadac"
path = "src/bin/namada-client/main.rs"

# Namada wallet
[[bin]]
doc = false
name = "namadaw"
path = "src/bin/namada-wallet/main.rs"

# Namada relayer
[[bin]]
doc = false
name = "namadar"
path = "src/bin/namada-relayer/main.rs"

[features]
default = ["namada/mainnet", "migrations"]
mainnet = ["namada_apps_lib/mainnet"]
jemalloc = ["namada_apps_lib/jemalloc"]
migrations = ["namada/migrations", "namada_apps_lib/migrations"]
namada-eth-bridge = ["namada_apps_lib/namada-eth-bridge"]

[dependencies]
namada = {path = "../namada"}
namada_apps_lib = {path = "../apps_lib"}

color-eyre.workspace = true
eyre.workspace = true
tokio = {workspace = true, features = ["full"]}
toml.workspace = true
tracing-subscriber = { workspace = true, features = ["std", "json", "ansi", "tracing-log"]}
tracing.workspace = true
zeroize.workspace = true
warp = "0.3.2"
bytes = "1.1.0"

[target.'cfg(windows)'.dependencies]
winapi.workspace = true

[dev-dependencies]
namada = {path = "../namada", default-features = false, features = ["testing", "wasm-runtime"]}
namada_test_utils = {path = "../test_utils"}

assert_matches = "1.5.0"
bit-set.workspace = true
proptest.workspace = true
test-log.workspace = true
tokio-test.workspace = true

[build-dependencies]
git2.workspace = true
