[package]
authors = ["Heliax <TODO@heliax.dev>"]
description = "Anoma apps"
edition = "2018"
name = "Anoma"
readme = "../README.md"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "anoma"
path = "src/lib/mod.rs"

# Anoma CLI that aggregates some common commands for the node and the client
[[bin]]
name = "anoma"
path = "src/bin/anoma/main.rs"

# Anoma node daemon
[[bin]]
name = "anomad"
path = "src/bin/anoma-node/main.rs"

# Anoma client
[[bin]]
name = "anomac"
path = "src/bin/anoma-client/main.rs"

[features]
default = ["std", "dev"]
# NOTE "dev" features that shouldn't be used in live networks are enabled by default for now
dev = []
std = ["ed25519-dalek/std", "rand/std", "rand_core/std"]

[dependencies]
anoma_shared = {path = "../shared"}
base64 = "0.13.0"
bech32 = "0.8.0"
blake2b-rs = "0.2.0"
borsh = "0.8.1"
byteorder = "1.4.2"
bytesize = "1.0.1"
# https://github.com/clap-rs/clap/issues/1037
clap = {git = "https://github.com/clap-rs/clap/", tag = "v3.0.0-beta.2"}
color-eyre = "0.5.10"
config = "0.9"
# TODO the older versions of rand and rand_core are currently required to avoid mismatching version issue (https://github.com/dalek-cryptography/ed25519-dalek/pull/159)
ed25519-dalek = {version = "1.0.1", default-features = false, features = ["rand", "u64_backend"]}
eyre = "0.6.5"
futures = "0.3"
hex = "0.4.2"
libp2p = "0.35.1"
log = "0.4.14"
parity-wasm = "0.42.2"
prost = "0.7.0"
prost-types = "0.7.0"
pwasm-utils = "0.17.0"
rand = {version = "0.7", default-features = false}
rand_core = {version = "0.5", default-features = false}
rayon = "1.5.0"
regex = "1.4.5"
rocksdb = "0.15"
serde = {version = "1.0.123", features = ["derive"]}
serde_bytes = "0.11.5"
serde_json = "1.0.62"
serde_regex = "1.1.0"
sha2 = "0.9.3"
sparse-merkle-tree = {git = "https://github.com/heliaxdev/sparse-merkle-tree", branch = "tomas/encoding", features = ["with_borsh"]}
# TODO Not yet released on crates
tendermint-abci = {git = "https://github.com/informalsystems/tendermint-rs"}
# must be the same version as in tendermint-abci
tendermint-proto = {git = "https://github.com/informalsystems/tendermint-rs"}
tendermint-rpc = {version = "0.18.0", features = ["http-client"]}
thiserror = "1.0.24"
tokio = {version = "1.2.0", features = ["full"]}
toml = "0.5.8"
tonic = "0.4.0"
tracing = "0.1.26"
tracing-subscriber = "0.2.18"
wasmer = "1.0.2"
wasmer-compiler-singlepass = "1.0.2"
wasmer-engine-jit = "1.0.2"
wasmparser = "0.77.0"

[dev-dependencies]
cargo-watch = "7.5.0"
tempdir = "0.3.7"
wasmer-vm = "1.0.2"

[build-dependencies]
tonic-build = {version = "0.4.0", features = ["prost"]}
