[package]
authors = ["Heliax AG <hello@heliax.dev>"]
description = "Anoma apps"
edition = "2018"
license = "GPL-3.0"
name = "anoma"
readme = "../README.md"
resolver = "2"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "anoma"
path = "src/lib/mod.rs"

# Anoma CLI that aggregates some common commands for the node and the client
[[bin]]
name = "anoma"
path = "src/bin/anoma/main.rs"

# Anoma node
[[bin]]
name = "anoman"
path = "src/bin/anoma-node/main.rs"

# Anoma client
[[bin]]
name = "anomac"
path = "src/bin/anoma-client/main.rs"

[features]
default = ["std", "dev"]
# NOTE "dev" features that shouldn't be used in live networks are enabled by default for now
dev = []
std = ["ed25519-dalek/std", "rand/std", "rand_core/std"]
# for integration tests and test utilies
testing = []

[dependencies]
anoma_shared = {path = "../shared", features = ["wasm-runtime"]}
base64 = "0.13.0"
bech32 = "0.8.0"
blake2b-rs = "0.2.0"
borsh = "0.9.0"
byteorder = "1.4.2"
bytesize = "1.0.1"
# https://github.com/clap-rs/clap/issues/1037
clap = {git = "https://github.com/clap-rs/clap/", tag = "v3.0.0-beta.2"}
color-eyre = "0.5.10"
config = "0.11.0"
# TODO the older versions of rand and rand_core are currently required to avoid mismatching version issue (https://github.com/dalek-cryptography/ed25519-dalek/pull/159)
ed25519-dalek = {version = "1.0.1", default-features = false, features = ["rand", "u64_backend", "serde"]}
eyre = "0.6.5"
futures = "0.3"
libp2p = "0.38.0"
prost = "0.7.0"
prost-types = "0.7.0"
# TODO the older versions of rand and rand_core are currently required to avoid mismatching version issue (https://github.com/dalek-cryptography/ed25519-dalek/pull/159)
rand = {version = "0.7", default-features = false}
rand_core = {version = "0.5", default-features = false}
rayon = "1.5.0"
regex = "1.4.5"
rocksdb = "0.16.0"
serde = {version = "1.0.125", features = ["derive"]}
serde_bytes = "0.11.5"
serde_json = "1.0.62"
serde_regex = "1.1.0"
sha2 = "0.9.3"
signal-hook = "0.3.9"
sparse-merkle-tree = {git = "https://github.com/heliaxdev/sparse-merkle-tree", branch = "tomas/encoding-0.9.0b", features = ["borsh"]}
# temporarily using fork work-around for https://github.com/informalsystems/tendermint-rs/issues/876 and, https://github.com/informalsystems/tendermint-rs/issues/896, https://github.com/informalsystems/tendermint-rs/issues/906, https://github.com/informalsystems/tendermint-rs/issues/907
tendermint = {git = "https://github.com/heliaxdev/tendermint-rs", branch = "tomas/config-opt-values"}
tendermint-abci = {git = "https://github.com/heliaxdev/tendermint-rs", branch = "tomas/config-opt-values"}
tendermint-proto = {git = "https://github.com/heliaxdev/tendermint-rs", branch = "tomas/config-opt-values"}
tendermint-rpc = {git = "https://github.com/heliaxdev/tendermint-rs", branch = "tomas/config-opt-values", features = ["http-client"]}
thiserror = "1.0.24"
tokio = {version = "1.2.0", features = ["full"]}
toml = "0.5.8"
tonic = "0.4.0"
tracing = "0.1.26"
tracing-log = "0.1.2"
tracing-subscriber = "0.2.18"
async-std = {version = "1.9.0", features = ["unstable"]}

[dev-dependencies]
anoma_shared = {path = "../shared", features = ["testing", "wasm-runtime"]}
cargo-watch = "7.5.0"
proptest = "1.0.0"
tempfile = "3.2.0"

[build-dependencies]
tonic-build = "0.4.0"
