<<<<<<< HEAD
[view_keys]
=======
[birthdays]

[view_keys]
albert-svk = "zvknam1qw7ysd8dqyqqpqp3rpe8e66t6y7elv4p5xgqh7904ck0ch87nsu8m3ftxnzzydg6l8q9yuzmczdgp9zjh4w8dtpmr880mn0r6wzefz35zdcucwqc8v2gz5cne222tszq20z9etczeeqs498zpjprfvkjl8uzqxcqp5a7665x6fuxdh8p8mn2haeryp8yjk4np6ka4xsdtmfw2hjwq3s7mk07pc6gjllc0u4yjnwu8fklf40rvcvgwqn6t87x97nd8ajqrgdffayv48q54ghg7"
bertha-svk = "zvknam1qw7ysd8dqgqqpqzvpu7a7edpt7rwfwk4y99f0j4ngvules039mt205ljusd0q5jcf6spkwcdgpruphr54exyxwsuxaxkdpgl60wnpa7vzzrsk3w94rqv3ul03efva6w3kvpucwcrmj8hravjhf0xg8nkyrl865hadhty5ye590gr7xempm62s38yw4nxepytnrjn6mnln7f0qgnhpkj5850nwrvqkpfygvvhy4wp9edm4j4haftmclvxeymcktepjul847klrasr6rctw0mw8"
christel-svk = "zvknam1qw7ysd8dqvqqpqxy9fcc0qc4ntgjz5rxnlds3ywqryel8xk9regvpynx0syfmmq8ngcagfgsd5g0rrlh0ux5trlsepwwlnhes24gx77zk3emft6nyxs6jjp7y6j2gph9h3y3utndzywsa365hfcj2em9svkgguu0hvm3ey4qj3y5hwr37vwmclchx8sztfc7547glxs9nhmtys78ysl5rekdqu8z0lw8cafejwj3ajce3vf86su2pa3pffrgqscmvacsehph82stsucn0r9gu"
>>>>>>> 52d0ebbd7c (Revert "ci: minors")

[spend_keys]

[payment_addrs]
<<<<<<< HEAD
=======
albert-pa = "znam1zsdp40r8e52vg33fyd4gg4tkcjvvmj554l24m76zn6404wkklpjluexvrmppz7jkr8t4vvwfyan"
bertha-pa-a = "znam13e60xy9n3ze7w385d00a5hzxp0qvwkg89kvqlv3gpv48h5n5w5d2shgqfjl5q0lp8zp9yx2kqvw"
bertha-pa-b = "znam1dz4wxnjwvyz0ymvptwgp2fkr0fsjsgcum28swj6nm9uajwa8rt0aynf0463q6h8cw4sqsd9rg6g"
christel-pa = "znam14gxuky9uh0md3uj7d3s60e2fwcne0nnu9w562lxjspdfvuawfjxuta4vp2nxv6rr9j72jmqpzf5"
>>>>>>> 52d0ebbd7c (Revert "ci: minors")

[secret_keys]
faucet-key = "unencrypted:00548aa8393422b88dce5f4be8ee0320638061c3e0649ada1b0dacbec4c0c75bb2"
frank-key = "unencrypted:00a08de8d33b9798328d2e4476fade49f515dc82754451fc6ef7060ea0bd1e8f1a"

[public_keys]
albert-key = "ED25519_PK_PREFIXtpknam1qquurf975axryz4sf0jmyxpknkxp4cs7g8e8ahhpw089u6j3q9dy6qssdhz"
bertha-key = "ED25519_PK_PREFIXtpknam1qrg6qx72e0vqhg8plg20hv97g3p3q092gl88jlngkly0hpmca2h2we44uzw"
christel-key = "ED25519_PK_PREFIXtpknam1qp7r3et2usz538fxzkm69h3awr7t0kgk7h6528za7pk4g2jldk5dz0qjkhx"
daewon = "ED25519_PK_PREFIXtpknam1qzdgg0q7c2szvx67q84r859axuwmyvsku0t9w97kwdvz7ff89xy4xrqxfmv"
ester = "ED25519_PK_PREFIXtpknam1qplr7n6ej99zyvzvjy0w726p0809m6a279a02rn5zw0c52k8wdw8q5gfc8y"
faucet-key = "ED25519_PK_PREFIXtpknam1qzh2d8vk9wvj2j63fa3cvjru9uldpdjctjjxpafl5r8vwwf56pdgyq0vra4"
validator-0-account-key = "ED25519_PK_PREFIXtpknam1qrulnacf6l6lt2vlpc8y2yudlgzs9hzrfa9p66fv4p7vk8utf6m4554t3ak"
frank-key = "ED25519_PK_PREFIXtpknam1qqwfpuvn8x7yqtquejhppef4vddv9ghusec2rkaxav38amamxaxpgj9cs79"

[derivation_paths]
albert-key = "m/44'/877'/0'/0'/0'"
<<<<<<< HEAD
bertha-key = "m/44'/877'/0'/0'/1'"
christel-key = "m/44'/877'/0'/0'/2'"
=======
albert-svk = "m/32'/877'/1'"
bertha-key = "m/44'/877'/0'/0'/1'"
bertha-svk = "m/32'/877'/2'"
christel-key = "m/44'/877'/0'/0'/2'"
christel-svk = "m/32'/877'/3'"
>>>>>>> 52d0ebbd7c (Revert "ci: minors")
daewon = "m/44'/877'/0'/0'/3'"
ester = "m/44'/877'/0'/0'/4'"
validator-0-account-key = "m/44'/877'/0'/0'/5'"

[addresses]
albert = "tnam1qye83lg3ncsen8wjedgz27rxjktn0gcrc574p78e"
bertha = "tnam1qyvmxf6r5e9gjtq2pwsndgq77hmx4vw2rghnmt8v"
christel = "tnam1q8wemh6ws8vctdyg3dh9339qusttefzp0qw0qhvm"
albert-key = "tnam1qq6qyugak0gd4up6lma8z8wr88w3pq9lgvfhw6yu"
bertha-key = "tnam1qp7z909dsdv4qw5jcasywzm9p7xa3qeqqghcjqxe"
christel-key = "tnam1qq8kszasdp30f2j2pkhz40zpfvztdakwqvkm0xy4"
daewon = "tnam1qqnxq04amahj5yuwux7pdsjp3dyu07at3u3f742p"
ester = "tnam1qr2y927swt2ax66m9fgc9ejs40m7m77rry53cvkv"
faucet-key = "tnam1qzgcl2znamndmku7ujw6e79dmvd4v7rfd5c89dfz"
validator-0 = "tnam1q9q3lph40w88cs5000k48thkw3f7s0m6mqrtfgss"
frank = "tnam1q9sx4ekzqaq3xdxtruxkm764nhl00cvcsc7df5jf"
frank-key = "tnam1qz0nvec686e9pks8ynhm5ddq8ke7j2eey50uagtr"

[pkhs]
7C22BCAD8359503A92C760470B650F8DD8832002 = "bertha-key"
3402711DB3D0DAF03AFEFA711DC339DD1080BF43 = "albert-key"
26603EBDDF6F2A138EE1BC16C2418B49C7FBAB8F = "daewon"
918FA853EEE6DDDB9EE49DACF8ADDB1B5678696D = "faucet-key"
0F680BB06862F4AA4A0DAE2ABC414B04B6F6CE03 = "christel-key"
D442ABD072D5D36B5B2A5182E650ABF7EDFBC319 = "ester"
E9A42797AA7E25F01F0DA8FCD1B69C8C76627715 = "validator-0-account-key"
9F36671A3EB250DA0724EFBA35A03DB3E92B3925 = "frank-key"

[address_vp_types]
