[book]
authors = ["Heliax R&D Team"]
edit-url-template = "https://github.com/anoma/anoma/edit/master/docs/{path}"
git-repository-url = "https://github.com/anoma/anoma"
language = "en"
multilingual = false
site-url = "https://anoma.github.io/anoma/"
src = "src"
title = "Anoma - Technical Specifications"

[output.html]
additional-css = ["assets/custom.css"]
additional-js = ["assets/mermaid.min.js", "assets/mermaid-init.js"]
mathjax-support = true

[output.html.search]
expand = true

[preprocessor]
[preprocessor.mermaid]
command = "mdbook-mermaid"
