# name: Security audit

# on:
#   push:
#     paths: 
#       - 'ledger/Cargo.toml'
#       - 'ledger/Cargo.lock'


# jobs:
#   security_audit:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ledger
  
#     steps:
#       - uses: actions/checkout@v1
#       - uses: actions-rs/audit-check@v1
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}