name: Rerun Test Command

on: 
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'The commit to test'
        required: true
        type: string
      command:
        description: 'The make command to run'
        required: true
        type: string

env:
  RUSTC_WRAPPER: sccache
  SCCACHE_S3_USE_SSL: ${{ secrets.CACHE_SSL }}
  GIT_LFS_SKIP_SMUDGE: 1
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: full
  SCCACHE_BUCKET: namada-cache
  SCCACHE_ENDPOINT: ${{ secrets.CACHE_ENDPOINT }}
  AWS_ACCESS_KEY_ID: ${{ secrets.CACHE_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.CACHE_SECRET_KEY }}
  AWS_REGION: us-east-1

jobs:
  test:
    runs-on: 
      group: namada-runners
      labels: ubuntu-22
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        nightly_version: [nightly-2024-05-15]
        mold_version: [2.4.0]
        make:
          - name: ABCI

    env:
      RUSTC_WRAPPER: sccache

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha }}
      - name: Install libudev
        run: sudo apt-get update && sudo apt-get -y install libudev-dev
      - name: Install Protoc
        uses: heliaxdev/setup-protoc@v2
        with:
          version: "25.0"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.4
        with:
          version: "v0.7.7"
      - name: Setup rust toolchain
        uses: oxidecomputer/actions-rs_toolchain@ad3f86084a8a5acf2c09cb691421b31cf8af7a36
        with:
          profile: default
          override: true
      - name: Setup rust nightly
        uses: oxidecomputer/actions-rs_toolchain@ad3f86084a8a5acf2c09cb691421b31cf8af7a36
        with:
          toolchain: ${{ matrix.nightly_version }}
          profile: default
      - name: Cache cargo registry
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-${{ github.job }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Start sccache server
        run: sccache --start-server
      - name: Install mold linker
        run: |
          wget -q -O- https://github.com/rui314/mold/releases/download/v${{ matrix.mold_version }}/mold-${{ matrix.mold_version }}-x86_64-linux.tar.gz | tar -xz
          mv mold-${{ matrix.mold_version }}-x86_64-linux/bin/mold  /usr/local/bin
      - name: Download MASP parameters
        run: |
          mkdir -p /home/runner/.masp-params
          curl -o /home/runner/.masp-params/masp-spend.params -L https://github.com/anoma/masp-mpc/releases/download/namada-trusted-setup/masp-spend.params\?raw\=true
          curl -o /home/runner/.masp-params/masp-output.params -L https://github.com/anoma/masp-mpc/releases/download/namada-trusted-setup/masp-output.params?raw=true
          curl -o /home/runner/.masp-params/masp-convert.params -L https://github.com/anoma/masp-mpc/releases/download/namada-trusted-setup/masp-convert.params?raw=true
      - name: Build wasm 
        run: npm install -g wasm-opt && make build-wasm-scripts
      - name: Run command ${{ inputs.command }}
        run: ${{ inputs.command }}
        env:
          NAMADA_MASP_PARAMS_DIR: /home/runner/.masp-params
          RUSTFLAGS: "-C linker=clang -C link-arg=-fuse-ld=/usr/local/bin/mold"
      - name: Print sccache stats
        if: always()
        run: sccache --show-stats || true
      - name: Stop sccache server
        if: always()
        run: sccache --stop-server || true
      - name: Clean cargo cache
        run: |
          cargo install cargo-cache --no-default-features --features ci-autoclean cargo-cache
          cargo-cache