name: Triggerable Tasks

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch name'
        required: true
        type: string
      total_tests:
        description: 'Total prop. test cases'
        required: false
        default: 150
        type: number

permissions:
  id-token: read
  contents: read
  pull-requests: write

env:
  GIT_LFS_SKIP_SMUDGE: 1
  CHAIN_BUCKET: anoma-iac-files-master

jobs:
  pos:
    runs-on: ${{ matrix.os }}
    timeout-minutes: ${{ matrix.make.timeout }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        mold_version: [2.1.0]
        make:
          - name: Run PoS state-machine tests
            command: make test-pos-sm
            timeout: 360
            cache_key: namada
            cache_version: v2

    env:
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
      SCCACHE_CACHE_SIZE: 100G
      SCCACHE_BUCKET: namada-sccache-master

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::375643557360:role/anoma-github-action-ci-master
          aws-region: eu-west-1
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Setup rust toolchain
        uses: oxidecomputer/actions-rs_toolchain@ad3f86084a8a5acf2c09cb691421b31cf8af7a36
        with:
          profile: default
          override: true
      - name: Cache cargo registry
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-${{ matrix.make.cache_key }}-${{ matrix.make.cache_version }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.make.cache_key }}-${{ matrix.make.cache_version }}-cargo-
      - name: Start sccache server
        run: sccache --start-server
      - name: Install mold linker
        run: |
          wget -q -O- https://github.com/rui314/mold/releases/download/v${{ matrix.mold_version }}/mold-${{ matrix.mold_version }}-x86_64-linux.tar.gz | tar -xz
          mv mold-${{ matrix.mold_version }}-x86_64-linux/bin/mold  /usr/local/bin
      - name: Run task `${{ matrix.make.name }}`
        run: ${{ matrix.make.command }}
        env:
          PROPTEST_CASES: ${{ inputs.total_tests }}
          RUSTFLAGS: "-C linker=clang -C link-arg=-fuse-ld=/usr/local/bin/mold"
      - name: Stats sccache server
        run: sccache --show-stats || true
      - name: Start sccache server
        run: sccache --stop-server || true
