name: Triggerable Antithesis

on: 
  workflow_dispatch:
    inputs:
      namada_docker_tag:
        description: 'The docker tag of the namada docker images'
        required: true
        type: string
      scenario_tester_docker_tag:
        description: 'The docker tag of the scenario tester image'
        required: true
        type: string
      workload_type:
        type: choice
        description: The type of workload to use (namada__pr__customer 3h, namada__nightly__customer 8h)
        options: 
        - namada__pr__customer
        - namada__nightly__customer

jobs:
  antithesis:
    runs-on: [ubuntu-latest]

    steps:
      - uses: antithesishq/antithesis-trigger-action@v0.2
        with:
          notebook_name: ${{ github.event.inputs.workload_type }}
          tenant: heliax
          username: ${{ secrets.ANTITHESIS_USER_NAME }}
          password: ${{ secrets.ANTITHESIS_PASSWORD }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          images: namada-config:${{ github.event.inputs.namada_docker_tag }},namada-genesis:${{ github.event.inputs.namada_docker_tag }},namada:${{ github.event.inputs.namada_docker_tag }},namada-scenario-tester:${{ github.event.inputs.scenario_tester_docker_tag }}